name: Build

on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        poetry-version: [1.1.11]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Download mujoco
        run: bash download_mujoco.sh
      - name: Install ubuntu dependencies
        run:  |
          sudo apt-get update -q \
              && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
              curl \
              git \
              libgl1-mesa-dev \
              libgl1-mesa-glx \
              libglew-dev \
              libosmesa6-dev \
              software-properties-common \
              net-tools \
              vim \
              virtualenv \
              wget \
              xpra \
              xserver-xorg-dev
      - name: Install poetry dependencies
        run: poetry install
      - name: Build wheels
        run: poetry run python setup1.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist
